import Head from "next/head";
import React from "react";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";

import Image from "next/image";


export default function Home() {
  const circularImages = [
    'tech/css.png',
    'tech/docker.png',
    'tech/figma.png',
    'tech/git.png',
    'tech/html.png',
    'tech/javascript.png',
    'tech/mongodb.png',
    'tech/nodejs.png',
    'tech/reactjs.png',
    'tech/typescript.png',
  ];

  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">My-Portfolio</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text-to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://drive.google.com/drive/folders/1ZXMnPVJ-oqkpWqgVXDw2iI-iYlR1gI7F"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Malek hammami&apos;s Portfolio
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              I&apos;m a full stack developer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Hi, I&apos;m a full stack developer with experience in TypeScript and JavaScript.
              I have expertise in frameworks such as Angular, React, and Node.js. 
              I&apos;m a fast learner and enjoy working closely with clients to develop efficient, scalable, and user-friendly solutions that address real-world problems.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://twitter.com/your_twitter_username" target="_blank" rel="noopener noreferrer">
                <AiFillTwitterCircle />
              </a>
              <a href="https://www.linkedin.com/in/hammami-malek-6a84441a7/" target="_blank" rel="noopener noreferrer">
                <AiFillLinkedin />
              </a>
              <a href="https://github.com/malak895" target="_blank" rel="noopener noreferrer">
                <AiFillGithub />
              </a>
            </div>

            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" alt="Developer Working" />
            </div>
          </div>
        </section>

    <div>

        <h3 className="text-3xl py-1 dark:text-white">Technology </h3>
        <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
        Highlighting Various <span className="text-teal-500"> Technologies </span> in my Portfolio,
        The portfolio technology is an essential aspect of my <span className="text-teal-500"> professional journey </span> , Thanks to cutting-edge tools and innovative techniques.
       </p>
     
      <div className="container">
  <div className="row">
    {circularImages.slice(0, 5).map((image, index) => (
      <div key={index} className="ball">
        <Image src={image} alt="Description of the image"  />
      </div>
    ))}
  </div>
  <div className="row">
    {circularImages.slice(5).map((image, index) => (
      <div key={index} className="ball">
        <Image src={image} alt="Description of the image"  />
      </div>
    ))}
  </div>
</div>

    </div>
   

        <section className="py-10">
       
        <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            Since the beginning of my journey as a new graduate, I&apos;ve been passionate about web development. 
              <span className="text-teal-500"> My expertise </span>
              extends across a wide range of services <span className="text-teal-500">including brand design,and  programming.  </span>
             
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            I am committed to delivering high-quality solutions and continuously expanding my skills to stay at the forefront of the ever-evolving technology landscape.
            </p>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
                <a href="https://github.com/">
              <Image
                 src={"../public/web1.png"}
                width={300}
                height={200}
                layout="responsive"
                alt="Web Image"
              />
            </a>
             

              <h4 className="py-4 text-teal-600">Car Rent</h4>
              <p className="text-gray-800 py-1">Web-based platform that allows users to search, book, and manage car rentals from various providers, providing a convenient and efficient solution for transportation needs.</p>
 
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
            <a href="https://malak895.github.io/netflix/">
              <Image
                src="../public/web3.png"
                width={300}
                height={200}
                layout="responsive"
                alt="Web Image"
              />
            </a>
              <h4 className="py-4 text-teal-600">Netflix </h4>
              <p className="text-gray-800 py-1">Our Netflix it is a replica of the famous video streaming service, created as part of my portfolio.</p>
             
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
            <a href="https://malak895.github.io/chatbotAi/">
              <Image
                src={"../public/web2.jpg "}
                width={300}
                height={200}
                layout="responsive"
                alt="Web Image"
              />
            </a>
             
              <h4 className="py-4 text-teal-600">Chatbot AI</h4>
              <p className="text-gray-800 py-1">chatbot AI is an AI program designed to simulate human-like conversations. It uses machine learning and natural language processing algorithms to understand .</p>
            
            </div>
          </div>
        </section>
      
      
     

      </main>
    

    

    </div>
  );
        
  


}
